[msg TestMsg [Ryuji]]
[s][bup 0 2 0 1 0][f 4 10 65535 0 0]This menu will allow you to choose where to begin[n]
[s]your [clr 9]experience[clr 0]. Choose a starting point carefully. [w][e]
[s]Please note that you cannot save progress, so[n]
[s]please make sure to complete a sector before quitting. [w][e]

[sel TestSelect]
Tom Cleary[e]
Good List[e]
Bad List[e]
Fun Facts[e]
Project Details[e]
Insight[e]

//Project details and Insight will be in the Hub.flow/msg files